# Set the problem type to interactive
type: default

# Specify the interactor source file
interactor: chk.cc

# Time and memory limits still apply to the contestant's solution
time: 1s
memory: 512m

# The subtasks section works the same way
subtasks:
  - score: 100
    n_cases: 20 # Looks for 1.in, 2.in, ... 5.in